# Generated by Django 3.2.7 on 2022-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(blank=True, max_length=30)),
                ('ItemCode', models.CharField(blank=True, max_length=30)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('UnitPrice', models.FloatField(blank=True, default=0)),
                ('Currency', models.CharField(blank=True, max_length=30)),
                ('HSN', models.CharField(blank=True, max_length=30)),
                ('TaxCode', models.FloatField(blank=True, default=0)),
                ('Discount', models.FloatField(blank=True, default=0)),
                ('Status', models.IntegerField(blank=True, default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
                ('UpdatedDate', models.CharField(blank=True, max_length=30)),
                ('UpdatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxName', models.CharField(blank=True, max_length=30)),
                ('TaxCode', models.FloatField(blank=True, default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
