# Generated by Django 3.2.7 on 2022-03-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_auto_20220309_1012'),
    ]

