# Generated by Django 3.2.7 on 2022-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0005_alter_item_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='UoM',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
