# Generated by Django 3.2.7 on 2022-03-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0007_rename_uom_item_uos'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Packing',
            field=models.CharField(blank=True, max_length=100),
        )
    ]
