import os
os.system("python3 manage.py makemigrations Lead")
os.system("python3 manage.py makemigrations Employee")
os.system("python3 manage.py makemigrations Company")
os.system("python3 manage.py makemigrations Branch")
os.system("python3 manage.py makemigrations corsheaders")
os.system("python3 manage.py makemigrations Opportunity")
os.system("python3 manage.py makemigrations BusinessPartner")
os.system("python3 manage.py makemigrations Demo")
os.system("python3 manage.py makemigrations Activity")
os.system("python3 manage.py makemigrations Countries")
os.system("python3 manage.py makemigrations Industries")
os.system("python3 manage.py makemigrations PaymentTermsTypes")
os.system("python3 manage.py makemigrations Quotation")
os.system("python3 manage.py makemigrations Order")
os.system("python3 manage.py makemigrations Item")
os.system("python3 manage.py makemigrations Notification")
os.system("python3 manage.py makemigrations Appsetting")
os.system("python3 manage.py migrate")
