# Generated by Django 3.2.7 on 2022-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField(blank=True, default=0)),
                ('WarehouseID', models.CharField(blank=True, max_length=30)),
                ('Add', models.IntegerField(blank=True, default=0)),
                ('Remove', models.IntegerField(blank=True, default=0)),
                ('Inventory', models.IntegerField(blank=True, default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Address', models.CharField(blank=True, max_length=30)),
                ('City', models.CharField(blank=True, max_length=30)),
                ('State', models.CharField(blank=True, max_length=30)),
                ('Pin', models.IntegerField(blank=True, default=0)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('Status', models.IntegerField(blank=True, default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
