# Generated by Django 3.2.7 on 2022-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='CreatedTime',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='UpdatedDate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='UpdatedTime',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
