# Generated by Django 3.2.7 on 2022-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_auto_20220223_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Emp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Remark',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Type',
            field=models.CharField(choices=[('Order', 'Order'), ('Transfer', 'Transfer'), ('Other', 'Other'), ('Undefined', 'Undefined')], default='Undefined', max_length=20),
        ),
    ]
