# Generated by Django 3.2.7 on 2022-02-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0003_auto_20220225_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Type',
            field=models.CharField(choices=[('Inventory', 'Inventory'), ('Order', 'Order'), ('Transfer', 'Transfer'), ('Other', 'Other'), ('Undefined', 'Undefined')], default='Undefined', max_length=20),
        ),
    ]
