# Generated by Django 3.2.7 on 2022-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('SourceType', models.CharField(blank=True, max_length=100)),
                ('SourceID', models.CharField(blank=True, max_length=10)),
                ('Emp', models.CharField(blank=True, max_length=4)),
                ('Read', models.CharField(blank=True, max_length=1)),
                ('SourceTime', models.CharField(blank=True, max_length=10)),
                ('CreatedDate', models.CharField(blank=True, max_length=10)),
                ('CreatedTime', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
