# Generated by Django 3.2.12 on 2022-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Push',
            field=models.IntegerField(default=0),
        ),
    ]
