# Generated by Django 3.2.7 on 2022-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyID', models.CharField(blank=True, max_length=50)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=20)),
                ('SalesEmployeeName', models.CharField(blank=True, max_length=50)),
                ('EmployeeID', models.CharField(blank=True, max_length=30)),
                ('userName', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('firstName', models.CharField(blank=True, max_length=20)),
                ('middleName', models.CharField(blank=True, max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=20)),
                ('Email', models.CharField(blank=True, max_length=35)),
                ('Mobile', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=20)),
                ('Active', models.CharField(blank=True, max_length=20)),
                ('passwordUpdatedOn', models.CharField(blank=True, max_length=30)),
                ('lastLoginOn', models.CharField(blank=True, max_length=30)),
                ('logedIn', models.CharField(blank=True, max_length=20)),
                ('reportingTo', models.CharField(blank=True, max_length=20)),
                ('FCM', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('monthYear', models.CharField(blank=True, max_length=50)),
                ('SalesPersonCode', models.IntegerField(default=0)),
                ('sale', models.FloatField(default=0)),
                ('sale_diff', models.FloatField(default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=20)),
                ('UpdatedDate', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
