# Generated by Django 3.2.7 on 2022-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='Capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
