# Generated by Django 3.2.12 on 2022-05-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='U_FAV',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='U_LEADID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='U_LEADNM',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
