# Generated by Django 3.2.12 on 2022-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0002_auto_20220531_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='U_FAV',
            field=models.CharField(default='No', max_length=10),
            preserve_default=False,
        ),
    ]
