# Generated by Django 3.2.12 on 2022-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0004_alter_opportunity_u_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='U_FAV',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
