# Generated by Django 3.2.7 on 2022-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SourceID', models.IntegerField(default=0)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('Comment', models.CharField(blank=True, max_length=250)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('RelatedTo', models.CharField(blank=True, max_length=100)),
                ('Emp', models.IntegerField(default=0)),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('From', models.CharField(blank=True, max_length=10)),
                ('To', models.CharField(blank=True, max_length=10)),
                ('Time', models.CharField(blank=True, max_length=10)),
                ('Allday', models.CharField(blank=True, max_length=200)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Host', models.CharField(blank=True, max_length=100)),
                ('Participants', models.CharField(blank=True, max_length=250)),
                ('Document', models.CharField(blank=True, max_length=250)),
                ('Repeated', models.CharField(blank=True, max_length=100)),
                ('Priority', models.CharField(blank=True, max_length=100)),
                ('ProgressStatus', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Followup', 'Followup'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('SourceType', models.CharField(choices=[('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Quotation', 'Quotation'), ('Order', 'Order'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('Status', models.IntegerField(default=0)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=250)),
                ('SourceID', models.CharField(blank=True, max_length=10)),
                ('SourceType', models.CharField(choices=[('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Quotation', 'Quotation'), ('Order', 'Order'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('Emp', models.CharField(blank=True, max_length=10)),
                ('Emp_Name', models.CharField(blank=True, max_length=50)),
                ('UpdateDate', models.CharField(blank=True, max_length=100)),
                ('UpdateTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(blank=True, max_length=100)),
                ('Long', models.CharField(blank=True, max_length=100)),
                ('Emp_Id', models.CharField(blank=True, max_length=10)),
                ('Emp_Name', models.CharField(blank=True, max_length=50)),
                ('UpdateDate', models.CharField(blank=True, max_length=100)),
                ('UpdateTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
