# Generated by Django 3.2.7 on 2022-03-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
