# Generated by Django 3.2.7 on 2022-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_maps_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
