# Generated by Django 3.2.12 on 2022-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Activity', '0004_auto_20220413_0647'),
    ]
    operations = [
        migrations.AddField(
            model_name='chatter',
            name='Type',
            field=models.CharField(blank=True, max_length=25),
        )
    ]
