# Generated by Django 3.2.12 on 2022-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_auto_20220622_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatter',
            name='Time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='maps',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
