INSERT INTO `Countries_countries` (`Code`, `Name`, `Capital`) VALUES
("AF", "Afghanistan", "Kabul"),
("AX", "Åland Islands", "Mariehamn"),
("AL", "Albania", "Tirana"),
("DZ", "Algeria", "Algiers"),
("AS", "American Samoa", "Pago Pago"),
("AD", "Andorra", "Andorra la Vella"),
("AO", "Angola", "Luanda"),
("AI", "Anguilla", "The Valley"),
("AG", "Antigua and Barbuda", "Saint John's"),
("AR", "Argentina", "Buenos Aires"),
("AM", "Armenia", "Yerevan"),
("AW", "Aruba", "Oranjestad"),
("AU", "Australia", "Canberra"),
("AT", "Austria", "Vienna"),
("AZ", "Azerbaijan", "Baku"),
("BS", "The Bahamas", "Nassau"),
("BH", "Bahrain", "Manama"),
("BD", "Bangladesh", "Dhaka"),
("BB", "Barbados", "Bridgetown"),
("BY", "Belarus", "Minsk"),
("BE", "Belgium", "Brussels"),
("BZ", "Belize", "Belmopan"),
("BJ", "Benin", "Porto-Novo"),
("BM", "Bermuda", "Hamilton"),
("BT", "Bhutan", "Thimphu"),
("BO", "Bolivia", "Sucre"),
("BQ", "Bonaire", "Kralendijk"),
("BA", "Bosnia and Herzegovina", "Sarajevo"),
("BW", "Botswana", "Gaborone"),
("BV", "Bouvet Island", ""),
("BR", "Brazil", "Brasília"),
("IO", "British Indian Ocean Territory", "Diego Garcia"),
("UM", "United States Minor Outlying Islands", ""),
("VG", "Virgin Islands (British)", "Road Town"),
("VI", "Virgin Islands (U.S.)", "Charlotte Amalie"),
("BN", "Brunei", "Bandar Seri Begawan"),
("BG", "Bulgaria", "Sofia"),
("BF", "Burkina Faso", "Ouagadougou"),
("BI", "Burundi", "Bujumbura"),
("KH", "Cambodia", "Phnom Penh"),
("CM", "Cameroon", "Yaoundé"),
("CA", "Canada", "Ottawa"),
("CV", "Cape Verde", "Praia"),
("KY", "Cayman Islands", "George Town"),
("CF", "Central African Republic", "Bangui"),
("TD", "Chad", "N'Djamena"),
("CL", "Chile", "Santiago"),
("CN", "China", "Beijing"),
("CX", "Christmas Island", "Flying Fish Cove"),
("CC", "Cocos (Keeling) Islands", "West Island"),
("CO", "Colombia", "Bogotá"),
("KM", "Comoros", "Moroni"),
("CG", "Republic of the Congo", "Brazzaville"),
("CD", "Democratic Republic of the Congo", "Kinshasa"),
("CK", "Cook Islands", "Avarua"),
("CR", "Costa Rica", "San José"),
("HR", "Croatia", "Zagreb"),
("CU", "Cuba", "Havana"),
("CW", "Curaçao", "Willemstad"),
("CY", "Cyprus", "Nicosia"),
("CZ", "Czech Republic", "Prague"),
("DK", "Denmark", "Copenhagen"),
("DJ", "Djibouti", "Djibouti"),
("DM", "Dominica", "Roseau"),
("DO", "Dominican Republic", "Santo Domingo"),
("EC", "Ecuador", "Quito"),
("EG", "Egypt", "Cairo"),
("SV", "El Salvador", "San Salvador"),
("GQ", "Equatorial Guinea", "Malabo"),
("ER", "Eritrea", "Asmara"),
("EE", "Estonia", "Tallinn"),
("ET", "Ethiopia", "Addis Ababa"),
("FK", "Falkland Islands", "Stanley"),
("FO", "Faroe Islands", "Tórshavn"),
("FJ", "Fiji", "Suva"),
("FI", "Finland", "Helsinki"),
("FR", "France", "Paris"),
("GF", "French Guiana", "Cayenne"),
("PF", "French Polynesia", "Papeetē"),
("TF", "French Southern and Antarctic Lands", "Port-aux-Français"),
("GA", "Gabon", "Libreville"),
("GM", "The Gambia", "Banjul"),
("GE", "Georgia", "Tbilisi"),
("DE", "Germany", "Berlin"),
("GH", "Ghana", "Accra"),
("GI", "Gibraltar", "Gibraltar"),
("GR", "Greece", "Athens"),
("GL", "Greenland", "Nuuk"),
("GD", "Grenada", "St. George's"),
("GP", "Guadeloupe", "Basse-Terre"),
("GU", "Guam", "Hagåtña"),
("GT", "Guatemala", "Guatemala City"),
("GG", "Guernsey", "St. Peter Port"),
("GN", "Guinea", "Conakry"),
("GW", "Guinea-Bissau", "Bissau"),
("GY", "Guyana", "Georgetown"),
("HT", "Haiti", "Port-au-Prince"),
("HM", "Heard Island and McDonald Islands", ""),
("VA", "Holy See", "Rome"),
("HN", "Honduras", "Tegucigalpa"),
("HK", "Hong Kong", "City of Victoria"),
("HU", "Hungary", "Budapest"),
("IS", "Iceland", "Reykjavík"),
("IN", "India", "New Delhi"),
("ID", "Indonesia", "Jakarta"),
("CI", "Ivory Coast", "Yamoussoukro"),
("IR", "Iran", "Tehran"),
("IQ", "Iraq", "Baghdad"),
("IE", "Republic of Ireland", "Dublin"),
("IM", "Isle of Man", "Douglas"),
("IL", "Israel", "Jerusalem"),
("IT", "Italy", "Rome"),
("JM", "Jamaica", "Kingston"),
("JP", "Japan", "Tokyo"),
("JE", "Jersey", "Saint Helier"),
("JO", "Jordan", "Amman"),
("KZ", "Kazakhstan", "Astana"),
("KE", "Kenya", "Nairobi"),
("KI", "Kiribati", "South Tarawa"),
("KW", "Kuwait", "Kuwait City"),
("KG", "Kyrgyzstan", "Bishkek"),
("LA", "Laos", "Vientiane"),
("LV", "Latvia", "Riga"),
("LB", "Lebanon", "Beirut"),
("LS", "Lesotho", "Maseru"),
("LR", "Liberia", "Monrovia"),
("LY", "Libya", "Tripoli"),
("LI", "Liechtenstein", "Vaduz"),
("LT", "Lithuania", "Vilnius"),
("LU", "Luxembourg", "Luxembourg"),
("MO", "Macau", ""),
("MK", "Republic of Macedonia", "Skopje"),
("MG", "Madagascar", "Antananarivo"),
("MW", "Malawi", "Lilongwe"),
("MY", "Malaysia", "Kuala Lumpur"),
("MV", "Maldives", "Malé"),
("ML", "Mali", "Bamako"),
("MT", "Malta", "Valletta"),
("MH", "Marshall Islands", "Majuro"),
("MQ", "Martinique", "Fort-de-France"),
("MR", "Mauritania", "Nouakchott"),
("MU", "Mauritius", "Port Louis"),
("YT", "Mayotte", "Mamoudzou"),
("MX", "Mexico", "Mexico City"),
("FM", "Federated States of Micronesia", "Palikir"),
("MD", "Moldova", "Chișinău"),
("MC", "Monaco", "Monaco"),
("MN", "Mongolia", "Ulan Bator"),
("ME", "Montenegro", "Podgorica"),
("MS", "Montserrat", "Plymouth"),
("MA", "Morocco", "Rabat"),
("MZ", "Mozambique", "Maputo"),
("MM", "Myanmar", "Naypyidaw"),
("NA", "Namibia", "Windhoek"),
("NR", "Nauru", "Yaren"),
("NP", "Nepal", "Kathmandu"),
("NL", "Netherlands", "Amsterdam"),
("NC", "New Caledonia", "Nouméa"),
("NZ", "New Zealand", "Wellington"),
("NI", "Nicaragua", "Managua"),
("NE", "Niger", "Niamey"),
("NG", "Nigeria", "Abuja"),
("NU", "Niue", "Alofi"),
("NF", "Norfolk Island", "Kingston"),
("KP", "North Korea", "Pyongyang"),
("MP", "Northern Mariana Islands", "Saipan"),
("NO", "Norway", "Oslo"),
("OM", "Oman", "Muscat"),
("PK", "Pakistan", "Islamabad"),
("PW", "Palau", "Ngerulmud"),
("PS", "Palestine", "Ramallah"),
("PA", "Panama", "Panama City"),
("PG", "Papua New Guinea", "Port Moresby"),
("PY", "Paraguay", "Asunción"),
("PE", "Peru", "Lima"),
("PH", "Philippines", "Manila"),
("PN", "Pitcairn Islands", "Adamstown"),
("PL", "Poland", "Warsaw"),
("PT", "Portugal", "Lisbon"),
("PR", "Puerto Rico", "San Juan"),
("QA", "Qatar", "Doha"),
("XK", "Republic of Kosovo", "Pristina"),
("RE", "Réunion", "Saint-Denis"),
("RO", "Romania", "Bucharest"),
("RU", "Russia", "Moscow"),
("RW", "Rwanda", "Kigali"),
("BL", "Saint Barthélemy", "Gustavia"),
("SH", "Saint Helena", "Jamestown"),
("KN", "Saint Kitts and Nevis", "Basseterre"),
("LC", "Saint Lucia", "Castries"),
("MF", "Saint Martin", "Marigot"),
("PM", "Saint Pierre and Miquelon", "Saint-Pierre"),
("VC", "Saint Vincent and the Grenadines", "Kingstown"),
("WS", "Samoa", "Apia"),
("SM", "San Marino", "City of San Marino"),
("ST", "São Tomé and Príncipe", "São Tomé"),
("SA", "Saudi Arabia", "Riyadh"),
("SN", "Senegal", "Dakar"),
("RS", "Serbia", "Belgrade"),
("SC", "Seychelles", "Victoria"),
("SL", "Sierra Leone", "Freetown"),
("SG", "Singapore", "Singapore"),
("SX", "Sint Maarten", "Philipsburg"),
("SK", "Slovakia", "Bratislava"),
("SI", "Slovenia", "Ljubljana"),
("SB", "Solomon Islands", "Honiara"),
("SO", "Somalia", "Mogadishu"),
("ZA", "South Africa", "Pretoria"),
("GS", "South Georgia", "King Edward Point"),
("KR", "South Korea", "Seoul"),
("SS", "South Sudan", "Juba"),
("ES", "Spain", "Madrid"),
("LK", "Sri Lanka", "Colombo"),
("SD", "Sudan", "Khartoum"),
("SR", "Suriname", "Paramaribo"),
("SJ", "Svalbard and Jan Mayen", "Longyearbyen"),
("SZ", "Swaziland", "Lobamba"),
("SE", "Sweden", "Stockholm"),
("CH", "Switzerland", "Bern"),
("SY", "Syria", "Damascus"),
("TW", "Taiwan", "Taipei"),
("TJ", "Tajikistan", "Dushanbe"),
("TZ", "Tanzania", "Dodoma"),
("TH", "Thailand", "Bangkok"),
("TL", "East Timor", "Dili"),
("TG", "Togo", "Lomé"),
("TK", "Tokelau", "Fakaofo"),
("TO", "Tonga", "Nuku'alofa"),
("TT", "Trinidad and Tobago", "Port of Spain"),
("TN", "Tunisia", "Tunis"),
("TR", "Turkey", "Ankara"),
("TM", "Turkmenistan", "Ashgabat"),
("TC", "Turks and Caicos Islands", "Cockburn Town"),
("TV", "Tuvalu", "Funafuti"),
("UG", "Uganda", "Kampala"),
("UA", "Ukraine", "Kiev"),
("AE", "United Arab Emirates", "Abu Dhabi"),
("GB", "United Kingdom", "London"),
("US", "United States", "Washington, D.C."),
("UY", "Uruguay", "Montevideo"),
("UZ", "Uzbekistan", "Tashkent"),
("VU", "Vanuatu", "Port Vila"),
("VE", "Venezuela", "Caracas"),
("VN", "Vietnam", "Hanoi"),
("WF", "Wallis and Futuna", "Mata-Utu"),
("EH", "Western Sahara", "El Aaiún"),
("YE", "Yemen", "Sana'a"),
("ZM", "Zambia", "Lusaka"),
("ZW", "Zimbabwe", "Harare");

