# Generated by Django 3.2.7 on 2022-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=35)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('natureOfIndustry', models.CharField(blank=True, max_length=100)),
                ('ERP', models.CharField(blank=True, max_length=100)),
                ('serverIP', models.CharField(blank=True, max_length=100)),
                ('port', models.IntegerField(default=0)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('license_limit', models.IntegerField(default=1)),
                ('active', models.IntegerField(default=1)),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
    ]
