# Generated by Django 3.2.7 on 2022-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_auto_20220302_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
