# Generated by Django 3.2.7 on 2022-03-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
