# Generated by Django 3.2.7 on 2022-03-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0006_lead_casetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='caseType',
        ),
    ]
