# Generated by Django 3.2.12 on 2022-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0007_remove_lead_casetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadID', models.CharField(blank=True, max_length=5)),
                ('UnitPrice', models.FloatField(default=0)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
                ('ItemDescription', models.CharField(blank=True, max_length=500)),
                ('ItemName', models.CharField(blank=True, max_length=500)),
                ('TaxCode', models.CharField(blank=True, max_length=10)),
            ],
        )
    ]
