# Generated by Django 3.2.12 on 2022-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0011_auto_20220620_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='alter_email',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lead',
            name='alter_phone',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
