# Generated by Django 3.2.13 on 2023-01-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0013_auto_20230124_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseType',
        ),
    ]
