# Generated by Django 3.2.13 on 2023-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0015_auto_20230124_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
