# Generated by Django 3.2.13 on 2023-05-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0016_auto_20230426_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.CharField(blank=True, max_length=150)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
                ('UpdateDate', models.CharField(blank=True, max_length=100)),
                ('UpdateTime', models.CharField(blank=True, max_length=100)),
                ('LeadId', models.IntegerField(default=0)),
                ('CreatedBy', models.IntegerField(default=0)),
                ('UpdatedBy', models.IntegerField(default=0)),
                ('Size', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
