# Generated by Django 3.2.7 on 2022-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='OrderID',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
